sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        IF5rH2LKcy0IzcyMiW7tARbW3eWVjTDL9AepzKENapJxKd9lOJFoeUFa2FqKRtpzXwFyVIvD78+8ngcUS0zkSxil+lZihZD7lmm+/53f9fl5+sTGcG8XXCF+bmDrhnzTEMeCxhnrrHE2e5sscPHq8q0+7YhaJfPlGWxrqjsPtnzY1se59pBKV2MFqiEajGL4iiRxgD8+aZCA5jsaWqnQPEiSn6c9FWgfslHqdiq0AFB0DdqP15bzNGR2Q7sKt52FHEII+e5lAj6xpJrPVUOUfw+cfBWjsBt/ixZz11QqSf64i+3PbYIRW2ze7u5xR0ixZ31i0xhgsHPBa6dJk9FkSEG03562VGiHrrDIKLljnOOwg9I7luhE0fPAxQM2op3UhOepkBTlNvoaMZnvffdF2QWaoaHODqOm6fJrVeujTisKdN9SUX92TjYavOTo9x1K0qHc2SaEQnSl9t5GKeflSovY3HUs8DvkrOhiDJZwKiSMuWuLKQ03fh5U5o907gzMFHSV8uxXv5Rihev9mDctnjSB+7HVcGNZrLHkWozfuuATirzn52z0UT240nZiJjkNTL7XfyOrdRPTKVUYpGuaCrhKhC8L0NjVjiWQ3RDj3vX953GbFslEf5ohcPS2wQiMr8y6KMztDZUdpG83JBknhiUGhLeqL0Ixby6FZOo/yoY=
    - secure: >-
        YmV+AdWmP+5ITNa+4ZIgecUPDj+VVsSZ9owc4kP/ln/TV5AClSgpmCqykX+4ylikk8ISjIH/YuaX0k5GVrZpF31HwxlU0D0/i73mMKcJLt3nlj39CAeCQfKjLwmGwOx6GGDOchA02cdYN9uOi9xPN0CUbg1dFc7qcKsNhiaiBxUbYzAi76d52sXfhvQow3xsllqV7ljPaVHnfjlF/17MWNQ1hjcBcWIAMtdhJnOPlMgfUOXk4zq2Ewm754sP25mIDMQGfOWD2nhm3hQvUlXxEQBIQVWOQFXkZSMB64qHWjwidCdXzZf4HCp3zfLCqBPtNnvxYeXLpU7+CSFB4X9ELcCsAtWZC+p7LB6HcR35WAlir08wbEm7IgvnRiP2magbuVMy6Hvyzx1NNdVkOf17OWr/nZT8WSY1UifmF5zic/9YihNgZXH092B8tLl9pQ8y4MRXYl903QVl9PKipoK2kOTcBDWJ+Pv35JPpPlKKR2GZHKA1yCClj+GaKMoKcSO3NM+IasSpAkWq6BiCv8INHZ1R4wCRlPwgebKwaoAmD7JsQB/0c6l8ZKpRr57Ez9krDRrXzusYI9icLEMdfc2Is/1Y4H/vqX633vhIGYEgOvBAkDC0BbvbHi8ljEicPEju8vuqW1xJpKtNAWGGrVMdJXeXCq6Cij5r2EfdP+aUbXo=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
